imports:
    - php

filter:
    paths: [src/]
    excluded_paths: [vendor/*, tests/*]

build:
    nodes:
        my-tests:
            environment:
                php:
                    version: 8.0
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
        coverage:
            tests:
                override:
                    -
                        command: "XDEBUG_MODE=coverage vendor/bin/phpunit"
                        coverage:
                            file: "build/coverage.clover"
                            format: "php-clover"
