imports:
    - php

filter:
    paths: [src/]
    excluded_paths: [vendor/*, tests/*]

build:
    nodes:
        my-tests:
            environment:
                php:
                    version: 8.0.9
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
    tests:
        override:
            -
                command: "XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-clover=build/coverage.clover"
                coverage:
                    file: "build/coverage.clover"
                    format: "php-clover"
